version: '3'
services:
  backend:
    container_name: tshit-planning-server
    build:
      context: .
    image: tshirt:lastest
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
#      - MONGODB_USERNAME=root
#      - MONGODB_PASSWORD=123
    network_mode: "host"
  db:
    image: mongo:latest
    container_name: tshirt-planning-mongo
    volumes:
      - ./db:/tshirt/db
    ports:
      - 27017:27017
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=123