spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    hikari:
      connection-timeout: 10000
      maximum-pool-size: 15
  jpa:
#    show_sql: true
#    generate-ddl: true
    hibernate:
      ddl-auto: update