spring:
  profiles:
    active: production
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  profiles: development
  datasource:
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 2

---

spring:
  profiles: production
  datasource:
    url: jdbc:${DATABASE_URL}

    hikari:
      connection-timeout: 10000
      maximum-pool-size: 15

