spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poker
    username: poker
    password: poker

    hikari:
      connection-timeout: 10000
      maximum-pool-size: 20
  jpa:
#    show_sql: true
#    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: poker