
spring:
  profiles:
    active: production
  jpa:
#    show_sql: true
#    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 5000
---

spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/poker
    username: poker
    password: poker

    hikari:
      connection-timeout: 10000
      maximum-pool-size: 2

---

spring:
  profiles: production
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    hikari:
      connection-timeout: 10000
      maximum-pool-size: 15

