name: deploy backend

on:
  push:
    branches: [ main ]
jobs:    
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: deploy
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ec2-user/tshirt-planning &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            docker build -t planning-poker:latest backend &&
            docker stop app && docker rm app &&
            docker run -d --name app --env-file /home/ec2-user/env.list --network appNetwork -p 8080:8080 planning-poker:latest
          '
