name: update frontend

on:
  workflow_dispatch:
  push:
    paths:
      - frontend/**
jobs:    
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: code
      
      - uses: actions/checkout@v3
        with:
          repository: verkhovin/poker
          token: ${{ secrets.GH_REP_TOKEN }}
          path: poker
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: |
          cd ./code/frontend
          npm ci
          npm run build
          cd ../../
          rm -rf ./poker/css/*
          rm -rf ./poker/js/*
          rm -f ./poker/*.html
          rm -f ./poker/*.ico
          cp -r ./code/frontend/target/dist/* ./poker/
          cp ./poker/index.html ./poker/404.html
          cd ./poker
          git config --global user.name "Github Actions"
          git config --global user.email "verkhovin@users.noreply.github.com"
          git add .
          git commit -m "update"
          git push
