name: update frontend

on:
  push:
    paths:
      - frontend/**
jobs:    
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: code
      
      - uses: actions/checkout@v3
        with:
          repository: verkhovin/poker
          token: ${{ secrets.GH_REP_TOKEN }}
          path: poker
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: |
        cd ./code/frontend
        npm ci
        npm run build
        cd ../../
        rm -rf ./poker/css/*
        rm -rf ./poker/js/*
        rm -f ./poker/*.html
        rm -f ./poker/*.ico
        cp ./code/frontend/target/dist/* ./poker/
        cd ./poker
        git commit -m "update"
        git push
